inhibit_all_warnings!
platform :ios, '8.0'
use_frameworks!

target 'Snake_Feitian' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Snake_Feitian

    pod 'SDWebImage'
    
    pod 'PureLayout'
    
    pod 'QMUIKit'
    
    pod 'Alamofire'
    
    pod 'SwiftyJSON'
    
    pod 'MJRefresh'
    
    pod 'SVProgressHUD'

end
